from __future__ import annotations

from enum import StrEnum


class EvidenceStatus(StrEnum):
    VERIFIED_NCRC_RULE = "VERIFIED_NCRC_RULE"
    VERIFIED_NCRC_SOURCE = "VERIFIED_NCRC_SOURCE"
    VERIFIED_SERVER_ENV = "VERIFIED_SERVER_ENV"
    VERIFIED_SERVER_RUN = "VERIFIED_SERVER_RUN"
    VERIFIED_NVIDIA = "VERIFIED_NVIDIA"
    VERIFIED_UNITREE = "VERIFIED_UNITREE"
    VERIFIED_PEER_REVIEWED = "VERIFIED_PEER_REVIEWED"
    VERIFIED_PREPRINT = "VERIFIED_PREPRINT"
    EXPERIMENT_OBSERVED = "EXPERIMENT_OBSERVED"
    DERIVED = "DERIVED"
    HYPOTHESIS = "HYPOTHESIS"
    UNVERIFIED = "UNVERIFIED"
    UNKNOWN = "UNKNOWN"
    CONFLICTED = "CONFLICTED"


ROBOTS = ("H1", "Go2")
MEMORY_SOFT_GB = 8.0
MEMORY_STRONG_GB = 9.5
MEMORY_HARD_GB = 10.5
HEAVY_OPERATION_SECONDS = 5.0
HASH_CHUNK_BYTES = 1024 * 1024

